name: flutter_error_report
description: A new Flutter package.
version: 0.0.1
author: ray zhangl00829@163.com
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_info: 0.4.0+2
  package_info: 0.4.0+6
  logging: 0.11.3+2
  dio: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
